theme: minima
title: Everything Code Related
author: Matthew J. Muscat
email: matthew.muscat@mail.mcgill.ca
description: > # this means to ignore newlines until "baseurl:"
  Welcome to all code related projects.

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  matthewjmuscat # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
